### ISSUE TITLE
Add interactive mode

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/changelogged#71]
Would be nice to go interactively over changelogged suggestions one by one with options to
- skip suggestion
- add a suggestion to the changelog
- expand a merge commit (e.g. PR) into constituent commits (to include some into changelog as subchanges); note that this can be recursive;
- ignore this change (ignore commit/PR, modify some file, see #70)
- ignore some/all files mentioned in this change (modify `changelogged.yaml`, see #70)

**Comment by viviag** [comment]
Notes:
Would be natural to pass through each changelog in order of checking. I tend not to write one change to multiple changelogs in one step.
Would be extra nice to have hotkeys for each action.
InteractiveActions as I see them now: skip - do not write and go to next; edit - integrate with nano somehow? - it seems to be main goal of all this method; expand - call to default function which must be separate thus; ignore commit/PR - reqiures `ToJSON` instances for `Config`; see changed files - call for `git diff-tree -m`; inside latter will be it's own selector with option to add this file to ignored.

Other important note: it will be very annoying to do it all in terminal mode. Would be easier to edit changelog manually. So it will be running in something like `brick`.

**Comment by viviag** [comment]
After it's implemented options will be splitted.
New workflow:
* optional preflight - display misses in simple format
```
changelogged --list-misses
```
* interactive mode with options to skip, always ignore this commit and expand - immediate writing to changelog on selection.
```
changelogged [--from-bc] 
```
* Optionally edit ChangeLog. Change levels are not inferrable from git (since #87 implemented if ever).
```
vim ChangeLog.md
```
* Bump-versions. If ChangeLog does not match configured levels using `--level`
```
changelogged bump-versions [--level] arg
```
* Commit, push and release.
`update-changelog`, `--expand-pr`, `--force`, `--suggest` will go away.
`--force` then must be unavailable outside of `bump-versions` command, not shown in autocomplete and not parsable. So `--from-bc` and `-from-version` must be unavailable inside.
Common options will stay.
